### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by brianamarie** [githubschool/june-26#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by jacquemf** [comment]
Got it. François

**Comment by anescum** [comment]
Hakuna Matata

**Comment by githubteacher** [comment]
👍

**Comment by norwald** [comment]
test comment

**Comment by gdebrito** [comment]
Great GitHub day to all present

**Comment by flaviaportinari** [comment]
flaviaportinari - Hi :)

**Comment by andy2680** [comment]
Moijen

**Comment by AYMENCARLOS** [comment]
Ping git

**Comment by arnaudolig** [comment]
Hello there

**Comment by jdelglise** [comment]
Hi

**Comment by duviviereib** [comment]
Hi

**Comment by jhoranieh** [comment]
Hello

**Comment by MorganeB** [comment]
Hi

**Comment by denisnoel** [comment]
Hi

**Comment by ghost** [comment]
hello

**Comment by eib-fabianburtard** [comment]
please send me the invitation ;-)

**Comment by tdelsaux** [comment]
hi

**Comment by florin-d** [comment]
Hello

**Comment by ghost** [comment]
If someone is interested to see what distributed versioning means check this https://www.youtube.com/watch?v=w3jLJU7DT5E
